# -*- coding: UTF-8 -*-
#  pylink
# create at 2015/10/4
# autor: qianqians
from pypopup import *
from pytext import *
from pybutton import *
from tools import *
import uuid

def msgbox(text):
	js = " var bgcolor = \"RGB(220, 220, 220)\";\n"
	js += " var iWidth = document.documentElement.clientWidth;\n"
	js += " var iHeight = document.documentElement.clientHeight;\n"
	js += " var msgmsgObj=document.createElement(\"div\");\n"
	js += " msgmsgObj.style.position=\"absolute\";\n"
	js += " msgmsgObj.style.top = (((iHeight)/2)-10).toString()+\"px\";\n"
	js += " msgmsgObj.style.left = (((iWidth - width)/2)-10).toString()+\"px\";\n"
	js += " msgmsgObj.style.width = (width+20).toString() + \"px\";\n"
	js += " msgmsgObj.style.borderStyle = \"solid\";\n"
	js += " msgmsgObj.style.borderWidth = \"1px\";\n"
	js += " msgmsgObj.style.borderColor = bgcolor;\n"
	js += " msgmsgObj.style.backgroundColor = bgcolor;\n"
	js += " msgmsgObj.style.filter = \"alpha(opacity=50)\";\n"
	js += " msgmsgObj.style.opacity=\"0.5\";\n"
	js += " var moveX = 0;\n"
	js += " var moveY = 0;\n"
	js += " var moveTop = 0;\n"
	js += " var moveLeft = 0;\n"
	js += " var moveable = false;\n"
	js += " msgmsgObj.onmouseover = function() {\n"
	js += "     msgmsgObj.style.cursor=\"move\";\n"
	js += " };\n"
	js += " msgmsgObj.onmouseout = function(){\n"
	js += "     msgmsgObj.style.cursor=\"auto\";\n"
	js += "     if (moveable) {\n"
	js += "         moveable = false;\n"
	js += "     }\n"
	js += " };\n"
	js += " msgmsgObj.onmousedown = function() {\n"
	js += "     moveable = true;\n"
	js += "     moveX = event.clientX;\n"
	js += "     moveY = event.clientY;\n"
	js += "     moveTop = parseInt(msgmsgObj.style.top);\n"
	js += "     moveLeft = parseInt(msgmsgObj.style.left);\n"
	js += " };\n"
	js += " var msgtable = document.createElement(\"div\");\n"
	js += " msgmsgObj.onmousemove = function() {\n"
	js += "     if (moveable) {\n"
	js += "         var x = moveLeft + event.clientX - moveX;\n"
	js += "         var y = moveTop + event.clientY - moveY;\n"
	js += "         msgmsgObj.style.left = x + \"px\";\n"
	js += "         msgmsgObj.style.top = y + \"px\";\n"
	js += "         msgtable.style.left = (x+10) + \"px\";\n"
	js += "         msgtable.style.top = (y+10) + \"px\";\n"
	js += "     }\n"
	js += " };\n"
	js += " msgmsgObj.onmouseup = function () {\n"
	js += "     if (moveable) {\n"
	js += "         moveable = false;\n"
	js += "         moveX = 0;\n"
	js += "         moveY = 0;\n"
	js += "         moveTop = 0;\n"
	js += "         moveLeft = 0;\n"
	js += "     }\n"
	js += " };\n"
	js += " msgtable.onmouseover = function() {\n"
	js += "     msgtable.style.cursor=\"move\";\n"
	js += " };\n"
	js += " msgtable.onmouseout = function(){\n"
	js += "     msgtable.style.cursor=\"auto\";\n"
	js += "     if (moveable) {\n"
	js += "         moveable = false;\n"
	js += "     }\n"
	js += " };\n"
	js += " msgtable.onmousedown = function() {\n"
	js += "     moveable = true;\n"
	js += "     moveX = event.clientX;\n"
	js += "     moveY = event.clientY;\n"
	js += "     moveTop = parseInt(msgmsgObj.style.top);\n"
	js += "     moveLeft = parseInt(msgmsgObj.style.left);\n"
	js += " };\n"
	js += " msgtable.onmousemove = function() {\n"
	js += "     if (moveable) {\n"
	js += "         var x = moveLeft + event.clientX - moveX;\n"
	js += "         var y = moveTop + event.clientY - moveY;\n"
	js += "         msgmsgObj.style.left = x + \"px\";\n"
	js += "         msgmsgObj.style.top = y + \"px\";\n"
	js += "         msgtable.style.left = (x+10) + \"px\";\n"
	js += "         msgtable.style.top = (y+10) + \"px\";\n"
	js += "     }\n"
	js += " };\n"
	js += " msgtable.onmouseup = function () {\n"
	js += "     if (moveable) {\n"
	js += "         moveable = false;\n"
	js += "         moveX = 0;\n"
	js += "         moveY = 0;\n"
	js += "         moveTop = 0;\n"
	js += "         moveLeft = 0;\n"
	js += "     }\n"
	js += " };\n"
	js += " msgtable.style.borderBottomStyle = \"solid\";\n"
	js += " msgtable.style.borderBottomWidth = \"1px\";\n"
	js += " msgtable.style.borderBottomColor = \"RGB(255, 255, 255)\";\n"
	js += " msgtable.style.borderLeftStyle = \"solid\";\n"
	js += " msgtable.style.borderLeftWidth = \"1px\";\n"
	js += " msgtable.style.borderLeftColor = \"RGB(255, 255, 255)\";\n"
	js += " msgtable.style.borderRightStyle = \"solid\";\n"
	js += " msgtable.style.borderRightWidth = \"1px\";\n"
	js += " msgtable.style.borderRightColor = \"RGB(255, 255, 255)\";\n"
	js += " msgtable.style.borderTopStyle = \"solid\";\n"
	js += " msgtable.style.borderTopWidth = \"1px\";\n"
	js += " msgtable.style.borderTopColor = \"RGB(255, 255, 255)\";\n"
	js += " msgtable.style.backgroundColor = \"RGB(255, 255, 255)\";\n"
	js += " msgtable.style.position=\"absolute\";\n"
	js += " msgtable.style.zIndex=\"1\";\n"
	js += " msgtable.style.top = ((iHeight)/2).toString()+\"px\";\n"
	js += " msgtable.style.left = ((iWidth - width)/2).toString()+\"px\";\n"
	js += " msgtable.style.width = width.toString() + \"px\";\n"
	js += " var msgtable_pop = document.createElement(\"div\");\n"
	js += " msgtable_pop.style.width = width.toString() + \"px\";\n"
	id = str(uuid.uuid4())
	js += " var table_" + id + " = document.createElement(\"div\");\n"
	js += " var texttable_" + id + " = document.createTextNode(\"" + text + "\");\n"
	js += " table_" + id + ".appendChild(texttable_" + id + ");\n"
	js += " table_" + id + ".style.margin=\"10px auto 10px 100px\";\n"
	js += " msgtable_pop.appendChild(table_" + id + ");\n"
	id = str(uuid.uuid4())
	js += " var table_" + id + " = document.createElement(\"input\");\n"
	js += " table_" + id + ".type = \"button\";\n"
	js += " table_" + id + ".value=\"确认\";\n"
	js += " table_" + id + ".style.margin=\"10px auto 10px 100px\";\n"
	js += " msgtable_pop.appendChild(table_" + id + ");\n"
	js += " msgtable.appendChild(msgtable_pop);\n"
	js += " document.body.appendChild(msgtable);\n"
	js += " msgmsgObj.style.height = (msgtable.offsetHeight +20).toString() + \"px\";\n"
	js += " document.body.appendChild(msgmsgObj);\n"

	return js
